#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WalkAlerts.Resource", IsApplication=true)]

namespace WalkAlerts
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_touch_helper_swipe_escape_velocity = 2130903042;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int InGameScreen = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int SearchButton = 2130968586;
			
			// aapt resource value: 0x7f040004
			public const int alertText = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int autoSearchText = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int clickerView = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int computerButton = 2130968581;
			
			// aapt resource value: 0x7f040010
			public const int connectButton = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int connectString = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int infoString = 2130968582;
			
			// aapt resource value: 0x7f040012
			public const int internetInfo = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int ipEditText = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_previous_elevation = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int multiText = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int portEditText = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int portTitleText = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int serverRecyclerView = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int statusText = 2130968587;
			
			// aapt resource value: 0x7f040011
			public const int textView1 = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int udpEditText = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AlertLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ComputerButtonView = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ConnectLayout = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Main = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int info_string = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int prohib_text = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
